2015-06-18T23:19:50.999837+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=selfiestats.herokuapp.com request_id=59f60596-decb-4d10-bc20-2e8774f2f0fc fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-18T23:43:22.725537+00:00 heroku[api]: Deploy e3a5380 by eater1234@gmail.com
2015-06-18T23:43:22.725537+00:00 heroku[api]: Release v15 created by eater1234@gmail.com
2015-06-18T23:43:22.780245+00:00 heroku[slug-compiler]: Slug compilation started
2015-06-18T23:43:22.780263+00:00 heroku[slug-compiler]: Slug compilation finished
2015-06-18T23:43:36.171280+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=selfiestats.herokuapp.com request_id=9dc07e95-ec2d-4287-bcc7-c294b4fb82c8 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-18T23:43:36.432665+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=selfiestats.herokuapp.com request_id=add22bd9-9877-47a2-bd3b-c637a2670533 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-18T23:52:51.784977+00:00 heroku[api]: Release v16 created by eater1234@gmail.com
2015-06-18T23:52:51.784977+00:00 heroku[api]: Deploy 6ba54d0 by eater1234@gmail.com
2015-06-18T23:52:51.851808+00:00 heroku[slug-compiler]: Slug compilation started
2015-06-18T23:52:51.851814+00:00 heroku[slug-compiler]: Slug compilation finished
2015-06-18T23:53:58.004802+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=selfiestats.herokuapp.com request_id=8caecc4d-3864-4a5a-8537-c906ddecdaf8 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-18T23:53:58.389231+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=selfiestats.herokuapp.com request_id=82b7cfb6-a35e-4d31-8bd7-b57e7c04f9c8 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:34:14.526181+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=selfiestats.herokuapp.com request_id=c3b85c4b-bfa6-467f-b5a6-9eb6ec676687 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:34:14.865165+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=selfiestats.herokuapp.com request_id=9232342d-dec7-4bf1-b7fe-a92708c580a9 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:38:57.552530+00:00 heroku[api]: Deploy 5dbe59c by eater1234@gmail.com
2015-06-19T00:38:57.552530+00:00 heroku[api]: Release v17 created by eater1234@gmail.com
2015-06-19T00:38:57.611196+00:00 heroku[slug-compiler]: Slug compilation started
2015-06-19T00:38:57.611235+00:00 heroku[slug-compiler]: Slug compilation finished
2015-06-19T00:39:28.304645+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=selfiestats.herokuapp.com request_id=9124fc50-0c49-47f7-9053-b562128c0ca5 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:39:28.594355+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=selfiestats.herokuapp.com request_id=a424b095-5899-49b9-9e1b-eacf0ac62e93 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:49:57.695800+00:00 heroku[api]: Scale to web=1 by eater1234@gmail.com
2015-06-19T00:50:04.326987+00:00 heroku[web.1]: Starting process with command `python app.py`
2015-06-19T00:50:06.047881+00:00 app[web.1]: Traceback (most recent call last):
2015-06-19T00:50:06.048295+00:00 app[web.1]:     msg = self.format(record)
2015-06-19T00:50:06.047907+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 859, in emit
2015-06-19T00:50:06.048300+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 732, in format
2015-06-19T00:50:06.048352+00:00 app[web.1]:     return fmt.format(record)
2015-06-19T00:50:06.048356+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 471, in format
2015-06-19T00:50:06.048384+00:00 app[web.1]:     record.message = record.getMessage()
2015-06-19T00:50:06.048388+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 335, in getMessage
2015-06-19T00:50:06.048411+00:00 app[web.1]:     msg = msg % self.args
2015-06-19T00:50:06.048434+00:00 app[web.1]: TypeError: %d format: a number is required, not str
2015-06-19T00:50:06.048438+00:00 app[web.1]: Logged from file _internal.py, line 87
2015-06-19T00:51:04.526245+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2015-06-19T00:51:04.526245+00:00 heroku[web.1]: Stopping process with SIGKILL
2015-06-19T00:51:05.314125+00:00 heroku[web.1]: Process exited with status 137
2015-06-19T00:51:05.325454+00:00 heroku[web.1]: State changed from starting to crashed
2015-06-19T00:51:05.325454+00:00 heroku[web.1]: State changed from crashed to starting
2015-06-19T00:51:14.397424+00:00 heroku[web.1]: Starting process with command `python app.py`
2015-06-19T00:51:19.089319+00:00 app[web.1]: Traceback (most recent call last):
2015-06-19T00:51:19.089457+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 859, in emit
2015-06-19T00:51:19.090099+00:00 app[web.1]:     msg = self.format(record)
2015-06-19T00:51:19.090105+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 732, in format
2015-06-19T00:51:19.090157+00:00 app[web.1]:     return fmt.format(record)
2015-06-19T00:51:19.090192+00:00 app[web.1]:     record.message = record.getMessage()
2015-06-19T00:51:19.090161+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 471, in format
2015-06-19T00:51:19.090244+00:00 app[web.1]:     msg = msg % self.args
2015-06-19T00:51:19.090195+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 335, in getMessage
2015-06-19T00:51:19.090271+00:00 app[web.1]: TypeError: %d format: a number is required, not str
2015-06-19T00:51:19.090276+00:00 app[web.1]: Logged from file _internal.py, line 87
2015-06-19T00:51:26.503152+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=selfiestats.herokuapp.com request_id=4219d272-d905-4742-8093-ad90cc7e7df1 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:52:14.992757+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2015-06-19T00:52:14.992757+00:00 heroku[web.1]: Stopping process with SIGKILL
2015-06-19T00:52:15.838204+00:00 heroku[web.1]: State changed from starting to crashed
2015-06-19T00:52:15.825079+00:00 heroku[web.1]: Process exited with status 137
2015-06-19T00:52:16.612054+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=selfiestats.herokuapp.com request_id=97a75d45-ede2-41ba-a313-50f5dfa19c35 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:52:17.346735+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=selfiestats.herokuapp.com request_id=eaaaa922-efd6-4628-97d2-66122474c31e fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:52:17.969201+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=selfiestats.herokuapp.com request_id=8df8bae4-15a0-4901-b0e2-5a6cb2876667 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:52:22.251290+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=selfiestats.herokuapp.com request_id=7820ae4f-0186-4178-bc21-999c7b409bb0 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:52:22.551573+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=selfiestats.herokuapp.com request_id=38d76358-2778-4c02-b3f7-819b0be3c12a fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:57:36.514284+00:00 heroku[slug-compiler]: Slug compilation started
2015-06-19T00:57:36.514301+00:00 heroku[slug-compiler]: Slug compilation finished
2015-06-19T00:57:36.466006+00:00 heroku[api]: Deploy 096962f by eater1234@gmail.com
2015-06-19T00:57:36.466006+00:00 heroku[api]: Release v18 created by eater1234@gmail.com
2015-06-19T00:57:36.554612+00:00 heroku[web.1]: State changed from crashed to starting
2015-06-19T00:57:45.342826+00:00 heroku[web.1]: Starting process with command `python app.py ${PORT}`
2015-06-19T00:57:48.020349+00:00 app[web.1]: Traceback (most recent call last):
2015-06-19T00:57:48.020375+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 859, in emit
2015-06-19T00:57:48.020773+00:00 app[web.1]:     msg = self.format(record)
2015-06-19T00:57:48.020804+00:00 app[web.1]:     return fmt.format(record)
2015-06-19T00:57:48.020778+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 732, in format
2015-06-19T00:57:48.020808+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 471, in format
2015-06-19T00:57:48.020833+00:00 app[web.1]:     record.message = record.getMessage()
2015-06-19T00:57:48.020836+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 335, in getMessage
2015-06-19T00:57:48.020865+00:00 app[web.1]:     msg = msg % self.args
2015-06-19T00:57:48.020886+00:00 app[web.1]: TypeError: %d format: a number is required, not str
2015-06-19T00:57:48.020887+00:00 app[web.1]: Logged from file _internal.py, line 87
2015-06-19T00:58:45.406385+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2015-06-19T00:58:45.406487+00:00 heroku[web.1]: Stopping process with SIGKILL
2015-06-19T00:58:46.614922+00:00 heroku[web.1]: Process exited with status 137
2015-06-19T00:58:46.633849+00:00 heroku[web.1]: State changed from starting to crashed
2015-06-19T00:58:48.028434+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=selfiestats.herokuapp.com request_id=4f06f6e8-a3b1-4b3a-9fb3-a465bbec81e0 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T00:58:48.482064+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=selfiestats.herokuapp.com request_id=288d8f03-b6af-4714-a974-63f8f64aa941 fwd="76.202.68.172" dyno= connect= service= status=503 bytes=
2015-06-19T01:08:50.875543+00:00 heroku[api]: Deploy 45f6c75 by eater1234@gmail.com
2015-06-19T01:08:50.875543+00:00 heroku[api]: Release v19 created by eater1234@gmail.com
2015-06-19T01:08:50.933720+00:00 heroku[slug-compiler]: Slug compilation started
2015-06-19T01:08:50.933744+00:00 heroku[slug-compiler]: Slug compilation finished
2015-06-19T01:08:50.986512+00:00 heroku[web.1]: State changed from crashed to starting
2015-06-19T01:08:57.239222+00:00 heroku[web.1]: Starting process with command `python app.py`
2015-06-19T01:08:59.486730+00:00 app[web.1]: Traceback (most recent call last):
2015-06-19T01:08:59.486756+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 859, in emit
2015-06-19T01:08:59.487178+00:00 app[web.1]:     msg = self.format(record)
2015-06-19T01:08:59.487185+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 732, in format
2015-06-19T01:08:59.487187+00:00 app[web.1]:     return fmt.format(record)
2015-06-19T01:08:59.487189+00:00 app[web.1]:     record.message = record.getMessage()
2015-06-19T01:08:59.487188+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 471, in format
2015-06-19T01:08:59.487191+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/logging/__init__.py", line 335, in getMessage
2015-06-19T01:08:59.487223+00:00 app[web.1]: TypeError: %d format: a number is required, not str
2015-06-19T01:08:59.487195+00:00 app[web.1]:     msg = msg % self.args
2015-06-19T01:08:59.487285+00:00 app[web.1]: Logged from file _internal.py, line 87
